### ISSUE TITLE
conform the breath mode of the led light on the arduino board

### ISSUE THREAD

**Issue by ADIYuchengCai** [ADIYuchengCai/DS4D-GROUP11#1]
@ShulongZheng 
I just check the file of the breath light. And I want to ask that you just give the different breath modes for the different lights?

I think we may need the same mode of breath light but different colors and frequency.

**Comment by ShulongZheng** [comment]
Yes, the different breathing patterns are just to test the effect of more breathing and ultimately to adopt a best visual effect

**Comment by ShulongZheng** [comment]
@ADIYuchengCai 
Yes, the different breathing patterns are just to test the effect of more breathing and ultimately to adopt a best visual effect

**Comment by ADIYuchengCai** [comment]
Ok, got it already receive the new code of the arduino board and the LED light.

Nice effect
