### ISSUE TITLE
Confirmation of connection between different xlsx files

### ISSUE THREAD

**Issue by ShulongZheng** [ADIYuchengCai/DS4D-GROUP11#2]
@ADIYuchengCai Does the file ' trees data for every plot.xlsx' contains the data in the pdf report?

**Comment by ADIYuchengCai** [comment]
No, it doesn't include the data from report. Just come from the  csv file and make the categories by plots on the map.

**Comment by ADIYuchengCai** [comment]
I also upload the report pdf file.
